# api version
version: '2'

services:
  api:
    build: ./api
    container_name: api
    environment:
      - VIRTUAL_HOST=api.${DOMAIN}
    image: api
    network_mode: "bridge"
    volumes:
      - ./
  jianyu:
    build: ./JavaScriptPractice
    container_name: jianyu
    environment:
        - VIRTUAL_HOST=jianyu.${DOMAIN},${DOMAIN}
    image: jianyu
    network_mode: "bridge"
    volumes:
        - ./Jianyu:/usr/share/nginx/html
